version: "3.8"

services:
  influxdb:
    image: influxdb:2.7
    container_name: airsense_db
    ports:
      - "8086:8086"
    volumes:
      - influxdb2_data:/var/lib/influxdb2
      - influxdb2_config:/etc/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin_airsense
      - DOCKER_INFLUXDB_INIT_PASSWORD=AirSense2025!
      - DOCKER_INFLUXDB_INIT_ORG=AirSense_Team
      - DOCKER_INFLUXDB_INIT_BUCKET=london_air_raw
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=airsense-secret-token-2025

  grafana:
    image: grafana/grafana:latest
    container_name: airsense_grafana
    depends_on:
      - influxdb
    ports:
      - "3000:3000"
    volumes:
      - C:/grafana-data:/var/lib/grafana   # 👈 EXISTING VOLUME
    restart: unless-stopped

volumes:
  influxdb2_data:
  influxdb2_config:
  # grafana-storage:
  #   external: true   # 👈 THIS IS THE KEY
